validation: pktio check for number of interfaces
CI got following error:
pktio.c: In function 'pktio_test_recv_queue':
pktio.c:643:11: error: 'pktio[0]' may be used uninitialized
	in this function [-Werror=maybe-uninitialized]
  pktio_tx = pktio[0]

That can never happen due to num_ifaces always > 1 in our test.
Add special check for that to make new gcc happy.

Signed-off-by: Maxim Uvarov <maxim.uvarov@linaro.org>
Reviewed-by: Christophe Milard <christophe.milard@linaro.org>