Timer: build fix for arm
source/odp_timer.c: In function ‘odp_timer_cancel_tmo’:wq!
source/odp_timer.c:136:3: error: format ‘%lu’ expects argument of type ‘long unsigned int’,
 but argument 8 has type ‘uint64_t’ [-Werror=format=]
   ODP_ERR("cancel failed for tim id %d tmo id :%d tick idx %lu\n", id, tmo, tick_idx);

odp_timer_ping.c: In function ‘ping_init’:
odp_timer_ping.c:257:31: error: cast increases required alignment of target type [-Werror=cast-align]
   dst_addr.sin_addr.s_addr = *(long *)hname->h_addr;

- Move ODP_ERR outside spinlock
- Replace ODP_ERR with ODP_DBG, as search_and_delete_tmo() func may
  fail for valid case like entry in list already deleted by timeout handler
  which is a valid case but then odp_err messaging is wrong..(pointed
  out by Ola). The invalid case still fall into same loop and may confuse
  for now, thus need to identify possible erronoing so to decode error message.
  I am leaving this open for now (possible errorno in timer implementation)
  ..will evolve in phases (TODO)

Signed-off-by: santosh shukla <santosh.shukla@linaro.org>