test: packet_gen: fix build with GCC 9
Ensure that destination string is null terminated by passing
size - 1 to strncpy. Strncpy copies all n chars to the destination
string if the source is longer than the destination.

error: 'strncpy' specified bound 24 equals destination size

Fixes: https://github.com/OpenDataPlane/odp/issues/930

Signed-off-by: Petri Savolainen <petri.savolainen@nokia.com>
Reviewed-by: Matias Elo <matias.elo@nokia.com>