Timer build fix
v2 titled patch "Timer-implementation-first-draft.patch"
missed out while merging that lead to build break.

| source/odp_timer.c: In function 'odp_timer_absolute_tmo':
| source/odp_timer.c:253:9: error: cast from pointer to integer
	of different size [-Werror=pointer-to-int-cast]
|   return (odp_timer_tmo_t) new_tmo;

this patch is diff of v1 vs v2 patch..Keeping original original
author v2 header copied from lng-odp list for reference.

commit 9258e038fca5f51c161d2dffc279569ffe99d02a
Author: Petri Savolainen <petri.savolainen@linaro.org>
Date:   Tue Mar 11 16:11:40 2014 +0200

    Timer implementation first draft

    Very simple implementation. Does not implement cancel_tmo. Test included into example app.

    Signed-off-by: Petri Savolainen <petri.savolainen@linaro.org>

Signed-off-by: santosh shukla <santosh.shukla@linaro.org>