test: build failure due to uninitialized variable
Build failure has been observed, as some flags, sub event
types were uninitialized.

error: ‘subtype’ may be used uninitialized \
		[-Werror=maybe-uninitialized]

Signed-off-by: Harman Kalra <hkalra@marvell.com>
Reviewed-by: Matias Elo <matias.elo@nokia.com>