linux-generic: Unbreak build due to missing timer_types.h
Fixes

  odp/timer.h:25:34: fatal error: odp/plat/timer_types.h: No such file or directory

Broke with

  18564de6fffd86fd28a7e58c688ba468d2131ec1

as far as I can see.

Signed-off-by: Simon Kagstrom <simon.kagstrom@netinsight.net>
Signed-off-by: Maxim Uvarov <maxim.uvarov@linaro.org>