configure: suppress pointer to packed structure warnings
Fix GCC-9 build by handling "pointer to packed member of
a struct" warnings not as errors. These warnings are generated
e.g. when taking pointers to protocol header structures, which
are defined with packed attribute. These structures are
naturally aligned, so these warnings can be ignored.

chksum.c: In function odph_process_l4_hdr:
chksum.c:133:43: error: taking address of packed member of
struct <anonymous> may result in an unaligned pointer
value [-Werror=address-of-packed-member]
pkt_chksum_ptr    = (uint16_t *)(void *)&udp_hdr_ptr->chksum;

                                        ^~~~~~~~~~~~~~~~~~~~

Signed-off-by: Petri Savolainen <petri.savolainen@nokia.com>