use proper type for 32 bit atomic test
Shift 64 bit 1ULL instead of 32 bit 1UL.

odp_test_atomic.c:89:2: error: left shift count >= width of type [-Werror]
  odp_atomic_store_u64(&a64, 1UL << 33);
  ^
odp_test_atomic.c: In function 'test_atomic_validate':
odp_test_atomic.c:104:2: error: left shift count >= width of type [-Werror]
  if (odp_atomic_load_u64(&a64) != 1UL << 33) {

Signed-off-by: Maxim Uvarov <maxim.uvarov@linaro.org>