example: classifier: use uint32_t instead of unsigned
Fixes build issue on arch where uint32_t != unsigned:
  example/classifier/odp_classifier.c:694:8: error:
    passing argument 3 of ‘parse_value’ from incompatible
    pointer type [-Werror] &stats[policy_count].rule.val_sz);

Signed-off-by: Nicolas Morey-Chaisemartin <nmorey@kalray.eu>
Reviewed-by: Balasubramanian Manoharan <bala.manoharan@linaro.org>
Signed-off-by: Maxim Uvarov <maxim.uvarov@linaro.org>