Revert "linux-generic: validation: fix dependency for tests-validation.env"
This reverts commit 000008f7f1de54a70d118f0ae56db48c47d60aff.
Missed to add Mike's review and this patch generates error:
ERROR: files left in build directory after distclean:
./platform/linux-generic/test/tests-validation.env

Reverting this commit until issue being resolved.

Signed-off-by: Maxim Uvarov <maxim.uvarov@linaro.org>